test:
  user-service:
    users: "[{\"id\":7, \"username\":\"abc\",\"password\":\"123\"},{\"id\":8, \"username\":\"def\",\"password\":\"456\"},{\"id\":9, \"username\":\"ghi\",\"password\":\"789\"}]"

spring:
  application:
    name: user-service
    
server:
  port: 3001
  
eureka:
  client:
    service-url: 
      defaultZone: http://127.0.0.1:2001/eureka
#负载均衡全局配置 
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  
#对特定服务负载均衡的配置  
user-service:
  ribbon:
    ConnectTimeout: 500
    ReadTimeout: 1000
    MaxAutoRetriesNextServer: 2
    MaxAutoRetries: 1
  
  
feign:
  hystrix:
    enabled: true

#降级，超过500毫秒调用降级方法
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500  
            
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream 